### ISSUE TITLE
Drone CI basics and advanced

### ISSUE THREAD

**Issue by tboerger** [k8s-nue-meetup/talks#11]
Hi orga team,

as already said on the last meetup I would like to talk about Drone CI. Last time we scratched the surface, this time I would like to talk about the install options for Drone CI, present the pretty new different runners and show the power of the Drone CI pipelines. Even if the Kubernetes runtime is currently experimental I would like to show that as well, and talk about the more flexible future of custom runners related to Kubernetes.

**Comment by obitech** [comment]
Thanks for your proposal @tboerger ! As discussed we would like to schedule your talk for the September Meetup, does that still work for you?

**Comment by tboerger** [comment]
Sure, that's exactly what I want :)

**Comment by obitech** [comment]
September it is then. Nice!

**Comment by obitech** [comment]
Thanks for your talk @tboerger , would you mind sending a PR with your slides?

**Comment by obitech** [comment]
Ok, could you just send a PR with the folder like `YYYY-MM-DD-<topic>` (like the others) and a `README.md` linking to your slides? Just so users will have an easy way of discovering it :)

**Comment by tboerger** [comment]
Sure

**Comment by tboerger** [comment]
Solved via https://github.com/k8s-nue-meetup/talks/pull/15
