### ISSUE TITLE
HA & high performance block storage with LINSTOR

### ISSUE THREAD

**Issue by raltnoeder** [k8s-nue-meetup/talks#19]
Not sure whether I am still within the deadline to submit a proposal for a talk. Anyway, here it is:

**HA & high performance block storage with LINSTOR**

_Based on the high availability & high performance replicated block storage provided by DRBD, LINSTOR adds the functionality of a software defined storage system that connects to Kubernetes infrastructure via the container storage interface (CSI). Distinctive features are the seperation of control plane and data plane, which allows upgrading and patching most software parts without I/O interruptions, and the availability of the technology under a free open source software license._

Some background:
LINSTOR is a storage cluster management product being developed by LINBIT starting in 2016 under the GPL license. It handles various types of storage layers, such as LVM, ZFS and NVMe over fabrics as backend storage pools, encryption, deduplication and replication based on DRBD on top of the backend storage.
The presentation gives an overview of the features of the software components of a software defined storage cluster based on LINSTOR, as well as an overview of the supported features and future roadmap.

**Comment by oz123** [comment]
@raltnoeder thanks for your submission!
I had just had a phone call with Timo. It's better that we postpone this one to Februar. 
The meetup will be on the 12 of February, and with earlier anouncement there will be higher participation in the meetup.

**Comment by oz123** [comment]
@meyerjom @obitech FYI.

**Comment by oz123** [comment]
@raltnoeder vielen Dank! Thanks for the talk. Would you like to share the slides with us?

**Comment by raltnoeder** [comment]
Hello, I can share the slides that I used, would you like me to send them to someone or upload them somewhere?

**Comment by oz123** [comment]
The best would be to make a PR with the slides ....

**Comment by raltnoeder** [comment]
Ok, should be ready by Monday (hope that's ok, I'm hosting a training currently, so I'm a bit slow)

**Comment by raltnoeder** [comment]
Sorry for the delay, see pull request #22
