### ISSUE TITLE
openSUSE Kubic - Nuremberg's Community k8s OS

### ISSUE THREAD

**Issue by sysrich** [k8s-nue-meetup/talks#3]
I'd like to give this talk to introduce openSUSE Kubic, a community-driven rolling release Linux distribution designed for running kubernetes clusters, with kubeadm (so this talk could be a good companion alongside #1)
This talk will be appropriate for beginners, but will also introduce how more advanced users can get involved with contributing to Kubic - being a community distribution, it's entirely mould-able in response to contributions.

Most of the core team behind Kubic are based in Nuremberg, so I'll try to bring a few of them along if the meetup approves this talk.

**Comment by oz123** [comment]
note: this talk is planned for June!

**Comment by obitech** [comment]
@sysrich thanks for your talk last time! Could you send a PR with your slides?
