### ISSUE TITLE
Building autonomous operations for Kubernetes with keptn

### ISSUE THREAD

**Issue by AloisReitbauer** [k8s-nue-meetup/talks#6]
While many platform-level operational tasks have been automated with Kubernetes and operators, managing individual microservices and applications is often still a highly manual task. Even cloud-native applications often rely on runbooks and hand-crafted pipelines. In many cases, these practices even differ from application to application. At Dynatrace we saw the same problem and built an open-source fabric for autonomous declarative operations called keptn. Keptn provides a ready-to-use framework for GitOps-based pipelines, standardized deployment models, monitoring and operations as a service. Keptn also allows automating operational tasks with runbook automation and self-healing. Although keptn has only been around for a short time, it is already the basis for declarative operations at large financial institutions and in the service delivery of global system integrators.

In this session, we'll share best practices for implementing a declarative automated operations approach. You'll learn how to build pipelines that never break a deployment stage and how to add smart self healing to your application. Last but not least, you'll get hands-on advice on how to add monitoring and operational knowledge to your pipeline artifacts. Even if you don’t plan to use keptn, you'll be able to apply these concepts for your cloud-native applications.

**Comment by oz123** [comment]
@AloisReitbauer Thank you for the submission. You prepare for holding your talk in our next meeting on June?

**Comment by AloisReitbauer** [comment]
Yes. This was/is the plan

**Comment by oz123** [comment]
@AloisReitbauer  are you still interested in giving this talk?

**Comment by obitech** [comment]
@AloisReitbauer please let us know if you would still like to hold the talk. Closing this issue in the meantime.
