### ISSUE TITLE
ExternalDNS

### ISSUE THREAD

**Issue by dklesev** [k8s-nue-meetup/talks#7]
Hey organizer team, 

We from [WhizUs](https://www.whizus.com/) would be happy if we could speak at some of your next meetups (multiple times fit too :)).

The following topics we can suggest:

- ExternalDNS
  - why one could need this
  - how it works
  - how to extend it with an own provider
- Kubernetes Operators
  - is one of the promising fields in k8s
  - how to write one (operator-sdk (or maybe more frameworks, depends on time))
  - run a DB in k8s?
- using only `kubectl` can be a bit tedious. We use some fancy tools like stern, krew, ksniff, kubeflow and are happy to introduce them

We can start from July if that fits for you.

Best regards,

Dimi

**Comment by oz123** [comment]
Hi Dimitry,
Thanks for the submissions! 
I would really like to hear about the ExternalDNS. Also are you up to speaking in the June meetup?

Thanks!

**Comment by dklesev** [comment]
Hey Oz,

Perfect, let's start wit ExternalDNS then. Unfortunately, I have no more time in June but starting from July (or later) is possible.
Maybe @erikauer could tell about operators in June :)
What do you think?

BR, Dimi

**Comment by erikauer** [comment]
He @oz123 and @dklesev,

I need to check my calendar. I come back to you tomorrow.

**Comment by erikauer** [comment]
@oz123 sorry for my delay. I could join your meetup next week on wednesday 12th june.

I could present the topic kubernetes operator framework, if this is interesting for you.

Please let me know if you have a free slot very soon, I need to book the flight on the same evening at 21:40.

**Comment by oz123** [comment]
@erikauer you are more then welcome to join our meetup!

**Comment by erikauer** [comment]
@oz123 thanks for the fast reply. 👍 Then I can book flights :)

**Comment by oz123** [comment]
@erikauer we have a go. I am going to publish the program and your talk is in.

**Comment by oz123** [comment]
Kubernetes External DNS on Exoscale - a Demo how to synchronize exposed Kubernetes Services and Ingresses with Exoscale DNS Service

**Comment by obitech** [comment]
Slides mergend with https://github.com/k8s-nue-meetup/talks/pull/9
