### ISSUE TITLE
Local k8s for developers - microk8s?

### ISSUE THREAD

**Issue by joergeb** [k8s-nue-meetup/talks#8]
sorry for bothering here (other ways to get in contact with meetup members?) but i'm looking for know how concerning simple single node kubernetes flavors for dev's, especially... no, not minikube, but microk8s.io provided by Canonical snap. any feedback appreciated

**Comment by obitech** [comment]
Hey Jorge,

thanks for your message, however this is probably not the right place to ask for support ;) You should try to ask your question on the official [Kubernetes Slack]. Alternatively you can come and ask me during the Meetup next Wednesday, maybe I can help you if you haven't solved it by then.
